/// <reference path="./externals.d.ts" />
/** Private acceptance seam. This is not included in the published browser entry. */
export { InputMachine, referenceDraftText, projectClipboard } from './input/machine'
export { SessionInputShell } from './input/facade'
export { ComposerSubmissionPolicy } from './input/submission-policy'
export { ComposerBlockRegistry } from './input/blocks'
export { createChatStore } from './stores'
export { contextOccupancy, formatTokens, formatDuration, cacheHitPercent, billedInputTokens, deriveStats } from './chat/StatsLine'
export { scrollFollowAtBottom as xhScrollFollowAtBottom } from './chat/ChatView'
export { TranscriptWindowRow as XhTranscriptWindowRow } from './chat/TranscriptWindowRow'
export { ComposerAddMenu as XHarnessComposerAddMenu } from './skeleton/ComposerAddMenu'
export { ContextMeter } from './skeleton/ContextMeter'
export { InputBar } from './skeleton/InputBar'
export { UserMessageNodeView, CompactionNodeView, RetryNodeView, TurnErrorNodeView, TurnMaxTokensNodeView } from './chat/MessageItem'
export { AssistantNodeView } from './chat/AssistantNodeView'
export { AssistantMarkdown } from './chat/AssistantMarkdown'
export { TurnTailNodeView, TurnProcessSummary } from './chat/TurnTailNodeView'
export { turnProcessPresentation } from './chat/turn-process'
export { turnTailDefinition } from './conversation-nodes/turn-tail'
export { registerConversationNodes } from './conversation-nodes/register'
export { isSessionEvent } from './contract/wire-event-codec'
export { TurnEndDataSchema, TurnEndDataInputSchema } from '../shared/generated/session-terminal'
export { ChatView } from './chat/ChatView'
export { ChatScrollMemory } from './chat/scroll-memory'
export { HistoryPageIntent } from './chat/history-page-intent'
export { ConversationRoot } from './skeleton/ConversationRoot'
export { xhEditStorage } from './edit/persistence'
export { xhForkMessage } from './edit/actions'
export { attachmentMediaType, attachmentKind, validateAttachments, browserDraftAttachment } from './attachments'
export { compactionDefinition } from './conversation-nodes/compaction'
export { commandDefinition } from './conversation-nodes/command'
export { messageDefinition } from './conversation-nodes/message'
export { checkpointDefinition as xhCheckpointDefinition } from './conversation-nodes/checkpoint'
export { CheckpointView as XhCheckpointView } from './chat/CheckpointView'
export { chatViewDefinition } from './conversation-nodes/chat-snapshot-builder'
export { en, zh, NS } from './locales'
export { apply, inject } from './apply'
export { ConversationController } from './service'
export { XHarnessMessageEditor } from './edit/MessageEditor'
export { XHarnessEditableInputBar } from './edit/EditableInputBar'
export { xhEditMessage } from './edit/actions'
export { ApprovalPanel } from './skeleton/ApprovalPanel'
export { ReasoningRow } from './chat/ReasoningRow'
export { QueueDock } from './queue/QueueDock'
export { InputHub } from './input/hub'

export { permissionFeedback, PermissionSelect } from './skeleton/PermissionSelect'

export { ConversationSessionHeader } from './skeleton/ConversationSession'

export { planToolFold, toolCanAutoFold } from './chat/adaptive-tool-fold'
