//! Host-only chat composition for Schedule's independent target seam. The
//! Schedule crate still owns time, reservations and run receipts; ordinary
//! Host/Agent paths own policy, model execution, history and live projection.
use crate::{rpc::permission_events, AgentSessionRequest, BasicHost, ModelRoute};
use async_trait::async_trait;
use serde_json::json;
use sha2::{Digest, Sha256};
use std::sync::Weak;
use xharness_agent::DurableAgentHandle;
use xharness_schedule::AutomationTargetProvider;
use xharness_session::{EventData, SessionMutationReceipt};

pub(crate) struct HostAutomationTargets(pub Weak<BasicHost>);
#[async_trait]
impl AutomationTargetProvider for HostAutomationTargets {
    async fn check_source(&self, source: &str) -> Result<(), String> {
        let host = self.0.upgrade().ok_or("automation Host is shutting down")?;
        let state = host.state.read().await;
        if state.archived_sessions.contains(source) || state.deleted_sessions.contains(source) {
            return Err("automation source is archived or deleted".into());
        }
        let session = state
            .sessions
            .get(source)
            .ok_or("automation source is unavailable")?;
        if session.dispatch_paused {
            return Err("automation source dispatch is paused".into());
        }
        Ok(())
    }
    async fn prepare(&self, source: &str, target: &str) -> Result<DurableAgentHandle, String> {
        self.check_source(source).await?;
        let host = self.0.upgrade().ok_or("automation Host is shutting down")?;
        host.hydrate_session(source)
            .await
            .map_err(|e| e.to_string())?;
        let (cwd, model, permission, preset) = {
            let state = host.state.read().await;
            let parent = state
                .sessions
                .get(source)
                .ok_or("automation source is unavailable")?;
            (
                parent.cwd.clone(),
                parent.model.clone(),
                parent.execution_permission(),
                parent.agent_preset.clone(),
            )
        };
        // Target ids are generated by Schedule from the reserved run id; no
        // model-controlled session-id field crosses this adapter.
        crate::rpc::session_lifecycle::create_with_visibility(
            &host,
            &json!({"sessionId":target,"cwd":cwd}),
            false,
        )
        .await
        .map_err(|e| e.message)?;
        let _guard = host.lock_admission(target).await;
        host.hydrate_session(target)
            .await
            .map_err(|e| e.to_string())?;
        let receipt_id = format!("{target}:origin");
        let snapshot = host
            .agent_runtime
            .authoritative_session(target)
            .await
            .map_err(|e| e.to_string())?
            .ok_or("automation target has no journal")?;
        let prior = snapshot.events().iter().find_map(|e| match e.data() {
            EventData::SessionMutationCommitted { receipt } if receipt.rpc_id == receipt_id => {
                Some(receipt)
            }
            _ => None,
        });
        if let Some(prior) = prior {
            if prior.method != "host.automation-target/v1"
                || prior.response["sourceSessionId"] != source
            {
                return Err("automation target identity conflict".into());
            }
        } else {
            let mut events = permission_events(permission);
            events.push(
                EventData::SessionModelSelected {
                    provider: model.provider.clone(),
                    model: model.model.clone(),
                    reasoning_effort: model.reasoning_effort.clone(),
                    context_window_tokens: model.context_window_tokens,
                }
                .into(),
            );
            if let Some(preset) = &preset {
                events.push(
                    EventData::AgentPresetSelected {
                        agent_preset: preset.clone(),
                    }
                    .into(),
                );
            }
            events.push(
                EventData::SessionMutationCommitted {
                    receipt: SessionMutationReceipt {
                        rpc_id: receipt_id,
                        method: "host.automation-target/v1".into(),
                        fingerprint: format!(
                            "{:x}",
                            Sha256::digest(json!([source, target]).to_string().as_bytes())
                        ),
                        response: json!({"sessionId":target,"sourceSessionId":source}),
                        response_event_seq_field: None,
                    },
                }
                .into(),
            );
            host.commit_session_events(target, events)
                .await
                .map_err(|e| e.message)?;
        }
        let request = {
            let mut state = host.state.write().await;
            let record = state
                .sessions
                .get_mut(target)
                .ok_or("automation target was removed")?;
            record.origin = Some("automation".into());
            let route = ModelRoute {
                provider: record.model.provider.clone(),
                model: record.model.model.clone(),
                reasoning_effort: record.model.reasoning_effort.clone(),
                context_window_tokens: record.model.context_window_tokens,
            };
            let permission = record.execution_permission();
            let cwd = record.cwd.clone();
            let prompt = state.prompt_assembly(target)?;
            AgentSessionRequest {
                session_id: target.into(),
                cwd,
                route,
                permission,
                prompt: Some(prompt),
            }
        };
        host.start_background_turn_listener();
        let handle = host
            .agent_runtime
            .prepare_automation_worker(request)
            .await
            .map_err(|e| e.to_string())?;
        // Recovery may reattach an already running/completed target. Publish
        // its actual snapshot; never reset a chat to blank on a prepare retry.
        let frame = {
            let state = host.state.read().await;
            let record = state
                .sessions
                .get(target)
                .ok_or("automation target was removed")?;
            json!({"type":"host/session-added","sessionId":target,"origin":"automation","blank":record.blank,"cwd":record.cwd,"agentPreset":record.agent_preset,"title":record.title})
        };
        host.push_host(frame);
        Ok(handle)
    }
}

pub(crate) fn restored_origin(session: &xharness_session::Session) -> bool {
    session.events().iter().any(|e|matches!(e.data(),EventData::SessionMutationCommitted {receipt} if receipt.method=="host.automation-target/v1"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{AgentRuntime, DurableLoopAgentRuntime, HostConfig, NoTools, PermissionPreset};
    use futures::stream;
    use std::{
        sync::{
            atomic::{AtomicUsize, Ordering},
            Arc,
        },
        time::Duration,
    };
    use tokio_util::sync::CancellationToken;
    use xharness_agent::MemoryLeaseManager;
    use xharness_core::{
        FinishReason, IdentityContextPolicy, ModelProvider, ProviderError, ProviderEvent,
        ProviderRequest, ProviderStream,
    };
    use xharness_schedule::{AutomationCommand, ScheduleManager};
    use xharness_session::{ScheduleChange, Store};

    struct Provider(AtomicUsize);
    #[async_trait]
    impl ModelProvider for Provider {
        async fn stream(
            &self,
            request: ProviderRequest,
            _: CancellationToken,
        ) -> Result<ProviderStream, ProviderError> {
            assert!(request
                .messages
                .iter()
                .any(|m| m.content.contains("[SCHEDULED USER TASK]")));
            self.0.fetch_add(1, Ordering::SeqCst);
            Ok(Box::pin(stream::iter([
                Ok(ProviderEvent::TextDelta("task result".into())),
                Ok(ProviderEvent::Completed {
                    finish_reason: Some(FinishReason::Stop),
                    usage: None,
                    provider_items: vec![],
                }),
            ])))
        }
    }
    #[tokio::test]
    async fn independent_task_uses_real_host_projection_and_jsonl_restart_without_reexecution() {
        let dir = std::env::temp_dir().join(format!(
            "xharness-automation-{}-{}",
            std::process::id(),
            crate::state::now_ms()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let store: Arc<dyn Store> = Arc::new(
            xharness_session_jsonl::JsonlSessionStore::new(dir.join("sessions"))
                .unwrap()
                .for_runtime(),
        );
        let provider = Arc::new(Provider(AtomicUsize::new(0)));
        let schedules = ScheduleManager::new(store.clone());
        let runtime = Arc::new(
            DurableLoopAgentRuntime::new(
                "test",
                "test-model",
                Some(provider.clone()),
                Arc::new(NoTools),
                Arc::new(IdentityContextPolicy),
                store.clone(),
                Arc::new(MemoryLeaseManager::default()),
                2048,
            )
            .with_schedules(schedules.clone()),
        );
        let mut config = HostConfig::new(&dir);
        config.provider_id = "test".into();
        config.model_id = "test-model".into();
        let host = BasicHost::with_agent_runtime(config.clone(), runtime.clone());
        crate::rpc::session_lifecycle::create(&host, &json!({"sessionId":"source"}))
            .await
            .unwrap();
        host.commit_session_events(
            "source",
            permission_events(PermissionPreset::WorkspaceWrite),
        )
        .await
        .unwrap();
        let created=schedules.execute("source","create",serde_json::from_value::<AutomationCommand>(json!({"action":"create","prompt":"check authorized training","mode":"task","target":"new_chat","after_seconds":1})).unwrap()).await;
        let id = created["id"].as_str().unwrap();
        let snapshot = store.load("source").await.unwrap().unwrap();
        let mut record = xharness_schedule::active_schedules(&snapshot)
            .unwrap()
            .remove(0);
        record.scheduled_at = (chrono::Utc::now() - chrono::Duration::seconds(1))
            .to_rfc3339_opts(chrono::SecondsFormat::Millis, true);
        store
            .append(
                "source",
                snapshot.revision(),
                vec![EventData::ScheduleChange {
                    change: ScheduleChange::Update {
                        version: 1,
                        schedule: record,
                    },
                }
                .into()],
            )
            .await
            .unwrap();
        store.flush("source").await.unwrap();
        host.sync_authoritative_session("source").await.unwrap();
        let mut frames = host.event_gateway.subscribe_mux();
        let mut announcements = host.event_gateway.subscribe_host();
        runtime
            .resume_session(AgentSessionRequest {
                session_id: "source".into(),
                cwd: dir.to_string_lossy().into(),
                route: ModelRoute::new("test", "test-model"),
                permission: PermissionPreset::WorkspaceWrite,
                prompt: None,
            })
            .await
            .unwrap();
        let view = tokio::time::timeout(Duration::from_secs(4), async {
            loop {
                let view = schedules
                    .execute("source", "view", AutomationCommand::View { id: id.into() })
                    .await;
                if view["runs"][0]["state"] == "completed" {
                    break view;
                }
                tokio::time::sleep(Duration::from_millis(10)).await;
            }
        })
        .await
        .unwrap();
        let target = view["runs"][0]["sessionId"].as_str().unwrap();
        let added = loop {
            let frame = announcements
                .try_recv()
                .expect("automation announcement missing");
            if frame.method == "host/session-added" && frame.payload["sessionId"] == target {
                break frame.payload;
            }
        };
        use xharness_api::{ApiBackend, RpcId, RpcMethod, RpcResult};
        let list = match host
            .call(
                RpcId::new("automation-wire"),
                RpcMethod::SessionList,
                json!({}),
                CancellationToken::new(),
            )
            .await
        {
            RpcResult::Success { value: Some(value) } => value,
            result => panic!("session.list failed: {result:?}"),
        };
        assert_eq!(added["origin"], "automation");
        assert!(list["items"]
            .as_array()
            .unwrap()
            .iter()
            .any(|row| row["sessionId"] == target && row["origin"] == "automation"));
        if let Ok(path) = std::env::var("XHARNESS_AUTOMATION_WIRE_EXPORT") {
            std::fs::write(
                path,
                serde_json::to_vec_pretty(&vec![json!({"added":added,"list":list})]).unwrap(),
            )
            .unwrap();
        }

        tokio::time::timeout(Duration::from_secs(3), async {
            loop {
                let frame = frames.recv().await.unwrap();
                if frame.payload.to_string().contains("task result") {
                    break;
                }
            }
        })
        .await
        .expect("real live Host projection missed the saved task output");
        assert_eq!(provider.0.load(Ordering::SeqCst), 1);
        {
            let state = host.state.read().await;
            assert_eq!(
                state.sessions[target].permission_preset,
                PermissionPreset::WorkspaceWrite
            );
            assert_eq!(state.sessions[target].model.model, "test-model");
            assert_eq!(state.sessions[target].cwd, state.sessions["source"].cwd);
            assert!(!state.sessions[target].delegated);
            assert_eq!(state.sessions[target].origin.as_deref(), Some("automation"));
        }
        host.stop_background_listeners();
        runtime.shutdown(Duration::from_secs(2)).await;
        drop(host);
        drop(runtime);
        drop(store);
        let reopened: Arc<dyn Store> = Arc::new(
            xharness_session_jsonl::JsonlSessionStore::new(dir.join("sessions"))
                .unwrap()
                .for_runtime(),
        );
        let schedules2 = ScheduleManager::new(reopened.clone());
        let runtime2 = Arc::new(
            DurableLoopAgentRuntime::new(
                "test",
                "test-model",
                Some(provider.clone()),
                Arc::new(NoTools),
                Arc::new(IdentityContextPolicy),
                reopened.clone(),
                Arc::new(MemoryLeaseManager::default()),
                2048,
            )
            .with_schedules(schedules2.clone()),
        );
        let host2 = BasicHost::with_agent_runtime(config, runtime2.clone());
        host2.restore_from_store(reopened.clone()).await.unwrap();
        let restored = schedules2
            .execute("source", "view", AutomationCommand::View { id: id.into() })
            .await;
        assert_eq!(restored["runs"], view["runs"]);
        assert_eq!(provider.0.load(Ordering::SeqCst), 1);
        assert_eq!(
            host2.state.read().await.sessions[target].origin.as_deref(),
            Some("automation")
        );
        host2.stop_background_listeners();
        runtime2.shutdown(Duration::from_secs(2)).await;
        drop(host2);
        drop(runtime2);
        drop(reopened);
        std::fs::remove_dir_all(dir).unwrap();
    }
}
