from pathlib import Path
import json
import argparse
parser=argparse.ArgumentParser()
parser.add_argument("--output",type=Path,default=Path(__file__).parent)
root=parser.parse_args().output
root.mkdir(parents=True,exist_ok=True)
products=[dict(id='orion',name='Orion Pro SSD',capacity='1TB',interface='NVMe PCIe 4.0',nand='TLC',warranty=5,tbw=650,price=549),dict(id='lyra',name='Lyra Plus SSD',capacity='1TB',interface='NVMe PCIe 4.0',nand='TLC',warranty=5,tbw=600,price=599),dict(id='nova',name='Nova Max SSD',capacity='1TB',interface='NVMe PCIe 4.0',nand='TLC',warranty=5,tbw=800,price=749),dict(id='qlc',name='Cloud Budget SSD',capacity='1TB',interface='NVMe PCIe 4.0',nand='QLC',warranty=5,tbw=200,price=399),dict(id='short',name='Rapid Mini SSD',capacity='1TB',interface='NVMe PCIe 4.0',nand='TLC',warranty=3,tbw=650,price=459),dict(id='gen3',name='Classic SSD',capacity='1TB',interface='NVMe PCIe 3.0',nand='TLC',warranty=5,tbw=650,price=429),dict(id='weak',name='Light SSD',capacity='1TB',interface='NVMe PCIe 4.0',nand='TLC',warranty=5,tbw=400,price=499),dict(id='small',name='Orion Small SSD',capacity='512GB',interface='NVMe PCIe 4.0',nand='TLC',warranty=5,tbw=650,price=349)]
for i in range(800):products.append(dict(id=f'other-{i}',name=f'Accessory {i:03}',capacity='-',interface='USB',nand='-',warranty=1,tbw=0,price=19+i%100))
(root/'catalog.json').write_text(json.dumps(products,indent=2))
html='''<!doctype html><html lang="en"><meta charset="utf-8"><title>XHarness Shopping Load Lab</title><style>body{font:16px system-ui;margin:0;background:#f5f6f8;color:#15181c}header{padding:18px 24px;background:#15181c;color:white;position:sticky;top:0;z-index:5}h1{font-size:20px;margin:0 0 12px}input,button,select{font:inherit;padding:8px;border:1px solid #aaa;border-radius:6px}button{cursor:pointer;background:white}main{padding:24px}nav{display:flex;align-items:center;gap:14px;flex-wrap:wrap;margin:14px 0}#grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}article{padding:18px;background:white;border-radius:10px;border:1px solid #ddd}h2{font-size:18px;margin:4px 0 10px}.price{font-size:24px;font-weight:700}.spec{display:block;font-size:14px;line-height:1.8}.actions{display:flex;gap:8px;align-items:center;margin-top:14px}#comparison,#cart{background:#fff;padding:14px;margin:14px 0;border:1px solid #ddd}#comparison:empty,#cart:empty{display:none}</style><header><h1>Shopping Load Lab — synthetic products, no payment</h1><form id="search"><label for="q">Search products</label> <input id="q" placeholder="Search products"> <button>Search</button> <button type="button" id="open-cart">Cart (<span id="count">0</span>)</button></form></header><main><nav><label><input type="checkbox" id="tlc">TLC only</label><label for="sort">Sort</label><select id="sort"><option value="default">Featured</option><option value="asc">Price: low to high</option><option value="desc">Price: high to low</option></select><button id="compare">Compare selected</button><span id="status" role="status"></span></nav><section id="comparison" aria-label="Comparison"></section><section id="cart" aria-label="Shopping cart"></section><section id="grid" aria-label="Products"></section></main><script>
const products=PRODUCTS; const chosen=new Set(),cart=[];const $=x=>document.getElementById(x); let query='',tlc=false,order='default';
function event(type,detail){fetch('/shop-event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,detail,cart:[...cart],query,tlc,order,utc:new Date().toISOString()})});}
function spec(p){return `${p.capacity} · ${p.interface} · ${p.nand} · Warranty ${p.warranty} years · Endurance ${p.tbw} TBW`;}
function render(){let list=products.filter(p=>(!query||p.name.toLowerCase().includes(query.toLowerCase()))&&(!tlc||p.nand==='TLC'));if(order==='asc')list.sort((a,b)=>a.price-b.price);if(order==='desc')list.sort((a,b)=>b.price-a.price);$('status').textContent=`${list.length} products`;$('grid').replaceChildren(...list.map(p=>{let a=document.createElement('article');a.innerHTML=`<h2>${p.name}</h2><div class="price">CNY ${p.price}</div><span class="spec">${spec(p)}</span><div class="actions"><label><input type="checkbox" aria-label="Compare ${p.name}">Compare</label><button aria-label="Add ${p.name} to cart">Add to cart</button></div>`;a.querySelector('input').checked=chosen.has(p.id);a.querySelector('input').onchange=e=>{if(e.target.checked)chosen.add(p.id);else chosen.delete(p.id);event('select_compare',{id:p.id,checked:e.target.checked})};a.querySelector('button').onclick=()=>{cart.push(p.id);$('count').textContent=cart.length;event('add_to_cart',{id:p.id});showCart();};return a;}));}
function showCart(){$('cart').textContent=cart.length?'Cart: '+cart.map(id=>{let p=products.find(p=>p.id===id);return p.name+' — CNY '+p.price}).join('; '):'Cart is empty';}
$('search').onsubmit=e=>{e.preventDefault();query=$('q').value;render();event('search',{});};$('tlc').onchange=e=>{tlc=e.target.checked;render();event('filter',{});};$('sort').onchange=e=>{order=e.target.value;render();event('sort',{});};$('compare').onclick=()=>{$('comparison').textContent='Comparison: '+products.filter(p=>chosen.has(p.id)).map(p=>p.name+' — CNY '+p.price+' — '+spec(p)).join(' | ');event('compare',{ids:[...chosen]});};$('open-cart').onclick=()=>{showCart();event('view_cart',{});};render();event('initial',{total:products.length,domNodes:document.querySelectorAll('*').length});
</script></html>'''.replace('PRODUCTS',json.dumps(products))
(root/'shop.html').write_text(html)
print('Catalog:',len(products),'products')
