import type {NativeInvoke} from '../shared/tauri'
import {useEffect,useRef,useState} from 'react'
import type {IApiClient, SettingsDescribeFace} from './contracts'
import {objectValue} from '../shared/runtime-types'
const REF='XHARNESS_MANAGED_API_TOKEN', ROUTE='xharness-managed', NS='llm-pi-ai'
export const managedLabels={
 zh:{nav:'账户与模型服务',title:'XHarness 模型服务',intro:'连接管理员分配的模型额度。自有模型配置不会改变。',connect:'连接账号',open:'打开登录网页',code:'连接代码',waiting:'在网页确认连接后，软件会自动接入。',done:'已连接。请在模型选择中选择 XHarness 服务。',cancel:'取消',disconnect:'移除本机连接',disconnectConfirm:'移除本机密钥？已授权设备仍可在账户网页撤销。',web:'请在桌面软件中连接账号。',error:'连接未完成，请重试或检查账号额度。',retry:'重试保存',manage:'账户与额度',clear:'在账户网页可撤销已授权设备。'},
 en:{nav:'Account & model service',title:'XHarness model service',intro:'Connect model allowance assigned by your administrator. Your own providers remain unchanged.',connect:'Connect account',open:'Open sign-in page',code:'Connection code',waiting:'Confirm in the website; the app will connect automatically.',done:'Connected. Select XHarness in the model picker.',cancel:'Cancel',disconnect:'Remove local connection',disconnectConfirm:'Remove this local credential? Authorized devices can still be revoked on the account website.',web:'Connect your account in the desktop app.',error:'Connection incomplete. Retry or check your model allowance.',retry:'Retry saving',manage:'Account & allowance',clear:'Revoke authorized devices on the account website.'}}
export async function saveManagedAccess(api:IApiClient,describe:SettingsDescribeFace,raw:unknown){
 const v=objectValue(raw);if(v.status!=='authorized'||typeof v.accessToken!=='string'||typeof v.baseURL!=='string'||!Array.isArray(v.models))throw Error('invalid_access')
 await describe.ensure();const snap=describe.getSnapshot();const ns=snap.view?.namespaces.find(n=>n.ns===NS);if(snap.status!=='ready'||!ns||!snap.view?.writable)throw Error('settings_unavailable')
 const existing=objectValue(objectValue(ns.value).providers)[ROUTE]
 if(existing!==undefined){const p=objectValue(existing);if(p.apiKeyEnv!==REF||p.baseURL!==v.baseURL||p.api!=='openai-completions')throw Error('provider_conflict')}
 const profile={displayName:'XHarness',api:'openai-completions',baseURL:v.baseURL,apiKeyEnv:REF,models:v.models}
 const write=await api.settings.mutate({ns:NS,expectedRevision:ns.revision,ops:[{op:'set',path:['providers',ROUTE],value:profile}]});if(!write.result.ok)throw Error('settings_write_failed');describe.acceptView(write.result.value)
 const stored=await api.credentials.set({ref:REF,value:v.accessToken});if(!stored.result.ok)throw Error('credential_store_failed')
}
export function ManagedAccount({api,describe,t}:{api:IApiClient;describe:SettingsDescribeFace;t:(key:string)=>string}){
 const invoke:NativeInvoke|undefined=window.__TAURI__?.core?.invoke
 const [flow,setFlow]=useState<{code:string;uri:string}|null>(null),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(false),[retry,setRetry]=useState(false)
 const alive=useRef(true),saving=useRef(false),halted=useRef(false)
 useEffect(()=>{alive.current=true;if(invoke)void invoke('desktop_account_status').then(raw=>{const v=objectValue(raw);if(alive.current&&typeof v.userCode==='string'&&typeof v.verificationUri==='string')setFlow({code:v.userCode,uri:v.verificationUri})}).catch(()=>{if(alive.current)setError(true)});void api.credentials.describe({refs:[REF]}).then(r=>{if(alive.current&&r.result.ok)setConnected(r.result.value.credentials[REF]?.configured===true)});return()=>{alive.current=false}},[api,invoke])
 useEffect(()=>{if(!flow||!invoke)return;let active=true;const tick=async()=>{if(saving.current||halted.current)return;saving.current=true;try{const raw=await invoke('desktop_account_poll');if(!active)return;const v=objectValue(raw);if(v.status==='authorized'){await saveManagedAccess(api,describe,raw);await invoke('desktop_account_finish',{saved:true});if(active){setConnected(true);setFlow(null);setError(false);setRetry(false)}}}catch{if(active){setError(true);setRetry(true);halted.current=true}}finally{saving.current=false}};const timer=setInterval(()=>{void tick()},5000);return()=>{active=false;clearInterval(timer)}},[flow,invoke,api,describe])
 async function start(){if(!invoke||busy)return;setBusy(true);setError(false);try{const v=objectValue(await invoke('desktop_account_start'));if(typeof v.userCode!=='string'||typeof v.verificationUri!=='string')throw Error();if(alive.current)setFlow({code:v.userCode,uri:v.verificationUri})}catch{if(alive.current)setError(true)}finally{if(alive.current)setBusy(false)}}
 async function cancel(){if(!invoke||saving.current||busy)return;setBusy(true);try{await invoke('desktop_account_finish',{saved:false});setFlow(null);setRetry(false);halted.current=false}catch{setError(true)}finally{setBusy(false)}}
 async function disconnect(){if(busy||!confirm(t('disconnectConfirm')))return;setBusy(true);try{const r=await api.credentials.unset({ref:REF});if(!r.result.ok)throw Error();setConnected(false)}catch{setError(true)}finally{setBusy(false)}}
 return <div className="xhe-root"><header><h2>{t('title')}</h2><p>{t('intro')}</p></header>{!invoke?<p>{t('web')}</p>:flow?<div><p>{t('code')}: <strong>{flow.code}</strong></p><button onClick={()=>void invoke('desktop_account_open').catch(()=>setError(true))}>{t('open')}</button><p>{t('waiting')}</p><button disabled={busy||saving.current} onClick={()=>void cancel()}>{t('cancel')}</button>{retry&&<button onClick={()=>{halted.current=false;setRetry(false);setError(false)}}>{t('retry')}</button>}</div>:connected?<div><p role="status">{t('done')}</p><button disabled={busy} onClick={()=>void disconnect()}>{t('disconnect')}</button><p>{t('clear')}</p></div>:<button disabled={busy} onClick={()=>void start()}>{t('connect')}</button>}{error&&<p role="alert">{t('error')}</p>}</div>
}
