import {useSyncExternalStore} from 'react'
import type {ManagedConnection} from './managed-connection'
export {saveManagedAccess} from './managed-connection'
export const managedLabels={
 zh:{nav:'账户与模型服务',title:'XHarness 模型服务',intro:'连接管理员分配的模型额度。自有模型配置不会改变。',connect:'登录 XHarness',open:'打开登录网页',code:'无法打开网页？使用连接代码',waiting:'请在浏览器登录并确认，完成后会返回软件。',done:'已连接。请在模型选择中选择 XHarness 服务。',cancel:'取消',disconnect:'移除本机连接',disconnectConfirm:'移除本机密钥？已授权设备仍可在账户网页撤销。',web:'请在桌面软件中连接账号。',error:'连接未完成，请重试或检查账号额度。',retry:'重试保存',manage:'账户与额度',clear:'在账户网页可撤销已授权设备。'},
 en:{nav:'Account & model service',title:'XHarness model service',intro:'Connect model allowance assigned by your administrator. Your own providers remain unchanged.',connect:'Sign in to XHarness',open:'Open sign-in page',code:'Cannot open the page? Use a connection code',waiting:'Sign in and confirm in your browser, then return to the app.',done:'Connected. Select XHarness in the model picker.',cancel:'Cancel',disconnect:'Remove local connection',disconnectConfirm:'Remove this local credential? Authorized devices can still be revoked on the account website.',web:'Connect your account in the desktop app.',error:'Connection incomplete. Retry or check your model allowance.',retry:'Retry saving',manage:'Account & allowance',clear:'Revoke authorized devices on the account website.'}}

export function ManagedAccount({controller,t}:{controller:ManagedConnection;t:(key:string)=>string}){
 const {native,flow,connected,busy,error,retry}=useSyncExternalStore(controller.subscribe,controller.getSnapshot)
 return <div className="xhe-root"><header><h2>{t('title')}</h2><p>{t('intro')}</p></header>{!native?<p>{t('web')}</p>:flow?<div><p>{t('waiting')}</p><button disabled={busy} onClick={()=>void controller.open()}>{t('open')}</button><details><summary>{t('code')}</summary><strong>{flow.code}</strong></details><button disabled={busy} onClick={()=>void controller.cancel()}>{t('cancel')}</button>{retry&&<button onClick={()=>controller.retry()}>{t('retry')}</button>}</div>:connected?<div><p role="status">{t('done')}</p><button disabled={busy} onClick={()=>{if(confirm(t('disconnectConfirm')))void controller.disconnect()}}>{t('disconnect')}</button><p>{t('clear')}</p></div>:<button disabled={busy} onClick={()=>void controller.start()}>{t('connect')}</button>}{error&&<p role="alert">{t('error')}</p>}</div>
}
