import CSS from './ToolRow.css'
if(typeof document!=='undefined'){const id='@xharness/dsh-client-ui-tool/ToolRow.module.css';if(document.querySelector('style[data-plugin-css='+JSON.stringify(id)+']')===null){const tag=document.createElement('style');tag.dataset.plugin='@xharness/dsh-client-ui-tool';tag.dataset.pluginCss=id;tag.textContent=CSS;document.head.appendChild(tag)}}
export default {
			"bodyScroll": "Dh215a_bodyScroll",
			"bodyWrap": "Dh215a_bodyWrap",
			"chevron": "Dh215a_chevron",
			"codeBody": "Dh215a_codeBody",
			"diffBody": "Dh215a_diffBody",
			"dsh-tool-row-sweep": "Dh215a_dsh-tool-row-sweep",
			"errorSummary": "Dh215a_errorSummary",
			"fileLink": "Dh215a_fileLink",
			"inspectButton": "Dh215a_inspectButton",
			"ioCard": "Dh215a_ioCard",
			"ioDivider": "Dh215a_ioDivider",
			"ioLabel": "Dh215a_ioLabel",
			"ioSection": "Dh215a_ioSection",
			"ioText": "Dh215a_ioText",
			"leading": "Dh215a_leading",
			"readBody": "Dh215a_readBody",
			"root": "Dh215a_root",
			"row": "Dh215a_row",
			"searchBody": "Dh215a_searchBody",
			"searchRecovery": "Dh215a_searchRecovery",
			"sep": "Dh215a_sep",
			"summary": "Dh215a_summary",
			"summarySuffix": "Dh215a_summarySuffix",
			"terminalBody": "Dh215a_terminalBody",
			"title": "Dh215a_title",
			"visuallyHidden": "Dh215a_visuallyHidden",
			"webBody": "Dh215a_webBody"
		}
