export const copy = {
  zh: {
    scheduled: "定时任务",
    newTask: "新建任务",
    upcoming: "即将执行",
    search: "搜索任务",
    searchPlaceholder: "搜索任务…",
    clearSearch: "清空搜索",
    filter: "筛选任务",
    closeMenu: "关闭菜单",
    all: "全部任务",
    enabled: "已启用",
    paused: "已暂停",
    taskList: "任务列表",
    showMore: "显示更多",
    showLess: "收起",
    noMatches: "没有找到匹配的任务",
    noTasks: "暂无任务",
    previewLabel: "界面预览 · 示例数据",
    memoryOnly: "刷新后重置",
    switchLanguage: "Switch to English",
    dark: "切换深色",
    light: "切换浅色",
    homeTitle: "安排一个任务",
    homeHelp: "让重复的工作按时进行，把注意力留给更重要的事。",
    openList: "打开任务列表",
    closeList: "关闭任务列表",
    back: "返回",
    edit: "编辑任务",
    confirm: "确认任务",
    editorHelp: "写清楚要做什么，再安排执行时间。",
    reviewHelp: "确认指令与时间，任务将在自己的会话中持续执行。",
    taskTitle: "任务名称",
    titlePlaceholder: "例如：检查训练日志",
    instruction: "任务指令",
    promptPlaceholder: "描述要检查的内容、判断条件，以及希望如何汇报…",
    schedule: "执行时间",
    every: "固定间隔",
    daily: "每天",
    weekly: "每周",
    once: "仅一次",
    interval: "间隔分钟数",
    minutes: "分钟",
    weekday: "星期",
    weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
    time: "执行时刻",
    timezone: "时区",
    minimum: "重复间隔至少 5 分钟",
    advanced: "高级设置",
    workspace: "工作区",
    runner: "执行位置",
    local: "本机",
    server: "服务器",
    modelNote: "模型与权限沿用会话配置。此预览不会连接执行端。",
    cancel: "取消",
    next: "下一步",
    nextRun: "下次执行",
    today: "今天",
    modify: "修改",
    savePreview: "保存示例",
    createPreview: "创建示例",
    confirmNote: "仅保存到当前预览，不会启动定时器或调用模型。",
    everyN: (n) => `每 ${n} 分钟`,
    errors: {
      title: "请填写任务名称。",
      prompt: "请填写任务指令。",
      interval: "请输入 5 到 525600 之间的整数分钟。",
      future: "请选择未来的执行时间。",
      time: "请选择有效的执行时刻。",
    },
    savedNote: "已保存示例任务；未创建真实自动化。",
    more: "更多操作",
    runDemo: "演示一次执行",
    deleteTask: "删除任务",
    noNext: "已暂停，不再触发后续执行",
    taskView: "任务内容",
    history: "执行记录",
    sampleHistory: "示例执行记录",
    notRun: "还没有执行记录",
    notRunHelp: "这里会展示每次运行的过程与结果。",
    justNow: "刚刚",
    sampleTime: "今天 13:45",
    sample: "示例",
    worked: (n) => `工作了 ${n} 秒`,
    sampleProcess: "示例步骤：读取日志 → 对比变化 → 汇总结果。未执行任何工具。",
    demoResult: "执行预览",
    seedResult: "本次检查摘要",
    demoBody:
      "这是一条界面演示记录，用于查看任务结果的排版。没有读取文件、连接服务器或请求模型。",
    seedBody:
      "训练持续运行，最新日志未出现需要立即处理的异常。后续继续关注吞吐变化与检查点生成。",
    seedPoint1: "训练进度与上次检查相比持续推进。",
    seedPoint2: "暂未发现异常退出；无需调整当前训练参数。",
    resultNote: "以上为示例内容，不代表真实监测结果。",
    offlineNote: "设计预览 · 未连接 Host，不会实际运行任务",
    toggleNote: "已切换示例状态；不影响真实任务。",
    runNote: "已添加示例记录；没有调用模型或执行命令。",
    deleteTitle: "删除这个示例任务？",
    deleteHelp: (title) =>
      `“${title}”会从预览列表移除。此操作不影响你的真实任务或对话。`,
    deletePreview: "删除示例",
    deletedNote: "已移除示例任务。",
  },
  en: {
    scheduled: "Scheduled",
    newTask: "New task",
    upcoming: "Upcoming",
    search: "Search tasks",
    searchPlaceholder: "Search tasks…",
    clearSearch: "Clear search",
    filter: "Filter tasks",
    closeMenu: "Close menu",
    all: "All tasks",
    enabled: "Enabled",
    paused: "Paused",
    taskList: "Task list",
    showMore: "Show more",
    showLess: "Show less",
    noMatches: "No matching tasks",
    noTasks: "No tasks yet",
    previewLabel: "Design preview · Sample data",
    memoryOnly: "Resets on reload",
    switchLanguage: "切换为中文",
    dark: "Switch to dark",
    light: "Switch to light",
    homeTitle: "Schedule a task",
    homeHelp: "Keep ongoing work moving, so you can focus on what matters.",
    openList: "Open task list",
    closeList: "Close task list",
    back: "Back",
    edit: "Edit task",
    confirm: "Confirm task",
    editorHelp: "Describe the work, then choose when it should run.",
    reviewHelp:
      "Review the instructions and timing. Each task keeps its own conversation.",
    taskTitle: "Task name",
    titlePlaceholder: "For example: Check training logs",
    instruction: "Instructions",
    promptPlaceholder:
      "Describe what to check, what matters, and how to report back…",
    schedule: "Schedule",
    every: "At an interval",
    daily: "Every day",
    weekly: "Every week",
    once: "Once",
    interval: "Interval in minutes",
    minutes: "minutes",
    weekday: "Day of week",
    weekdays: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    time: "Run time",
    timezone: "Time zone",
    minimum: "Minimum repeat interval: 5 minutes",
    advanced: "Advanced settings",
    workspace: "Workspace",
    runner: "Run on",
    local: "This computer",
    server: "Server",
    modelNote:
      "Inherit the conversation’s model and permissions. No execution host is connected in this preview.",
    cancel: "Cancel",
    next: "Next",
    nextRun: "Next run",
    today: "Today",
    modify: "Edit",
    savePreview: "Save sample",
    createPreview: "Create sample",
    confirmNote:
      "Saved in this preview only. No timer starts and no model is called.",
    everyN: (n) => `Every ${n} minutes`,
    errors: {
      title: "Enter a task name.",
      prompt: "Enter task instructions.",
      interval: "Enter a whole number from 5 to 525600 minutes.",
      future: "Choose a future time.",
      time: "Choose a valid run time.",
    },
    savedNote: "Sample task saved. No real automation was created.",
    more: "More actions",
    runDemo: "Demo one run",
    deleteTask: "Delete task",
    noNext: "Paused. Future runs will not be triggered.",
    taskView: "Task content",
    history: "Runs",
    sampleHistory: "Sample run history",
    notRun: "No runs yet",
    notRunHelp: "Each run’s work and results will appear here.",
    justNow: "Just now",
    sampleTime: "Today 13:45",
    sample: "Sample",
    worked: (n) => `Worked for ${n}s`,
    sampleProcess:
      "Sample steps: Read logs → Compare changes → Summarize. No tools were executed.",
    demoResult: "Execution preview",
    seedResult: "Check summary",
    demoBody:
      "This sample record demonstrates the result layout. No files were read, servers connected, or models called.",
    seedBody:
      "Training is progressing. The latest sample logs show no urgent exceptions. Continue watching throughput and checkpoint creation.",
    seedPoint1: "Training has progressed since the last sample check.",
    seedPoint2:
      "No unexpected exit is shown. No parameter changes are suggested.",
    resultNote: "Sample content, not actual monitoring results.",
    offlineNote: "Design preview · No Host connected. Tasks will not run.",
    toggleNote: "Sample status changed. Real tasks are unaffected.",
    runNote: "Sample record added. No models or commands were executed.",
    deleteTitle: "Delete this sample task?",
    deleteHelp: (title) =>
      `“${title}” will be removed from this preview. Your real tasks and conversations are unaffected.`,
    deletePreview: "Delete sample",
    deletedNote: "Sample task removed.",
  },
};
export const templates = {
  zh: [
    {
      title: "仓库更新",
      description: "每天整理提交与 PR，把值得关注的变化告诉我。",
      prompt:
        "整理工作区仓库最近的提交与 PR，汇总值得关注的变化和需要处理的问题。",
      kind: "daily",
    },
    {
      title: "训练监测",
      description: "定期检查训练日志，出现异常时及时汇报。",
      prompt:
        "检查训练日志与运行状态，仅在进度有重要变化或出现异常时汇报。不要修改训练参数。",
      workspace: "training",
      minutes: "30",
    },
    {
      title: "研究追踪",
      description: "每周整理新论文、实验进展与值得深入的方向。",
      prompt:
        "整理本周的研究材料与实验进展，列出值得深入阅读的论文和后续问题。",
      workspace: "research",
      kind: "weekly",
    },
    {
      title: "工作摘要",
      description: "每天回顾工作记录，整理进展与下一步安排。",
      prompt:
        "回顾工作区当天的工作记录，汇总完成事项、未解决问题与下一步安排。",
      kind: "daily",
    },
    {
      title: "测试巡检",
      description: "定期运行指定测试，汇总失败与潜在回归。",
      prompt:
        "运行工作区已约定的测试命令，整理失败项与潜在回归。不要自动修改代码。",
      minutes: "60",
    },
    {
      title: "服务检查",
      description: "检查服务可用性，只在需要关注时通知。",
      prompt:
        "检查已配置服务的可用性与错误日志，仅在异常或恢复时汇报。不自动重启服务。",
      minutes: "15",
    },
  ],
  en: [
    {
      title: "Repository updates",
      description:
        "A daily roundup of commits, PRs, and changes worth a closer look.",
      prompt:
        "Summarize recent commits and PRs in the workspace repository. Highlight important changes and items needing attention.",
      kind: "daily",
    },
    {
      title: "Training monitor",
      description:
        "Check training logs regularly and flag changes that need attention.",
      prompt:
        "Check training logs and runtime status. Report meaningful progress or exceptions only. Do not change training parameters.",
      workspace: "training",
      minutes: "30",
    },
    {
      title: "Research updates",
      description:
        "A weekly shortlist of papers, experiments, and ideas to explore.",
      prompt:
        "Summarize this week’s research materials and experiments. Shortlist papers worth reading and open questions.",
      workspace: "research",
      kind: "weekly",
    },
    {
      title: "Daily work summary",
      description:
        "Review progress, open questions, and what to focus on next.",
      prompt:
        "Review today’s workspace records. Summarize completed work, open issues, and next steps.",
      kind: "daily",
    },
    {
      title: "Test check-in",
      description:
        "Run the agreed test suite and surface failures or regressions.",
      prompt:
        "Run the workspace’s agreed test commands. Summarize failures and potential regressions. Do not modify code.",
      minutes: "60",
    },
    {
      title: "Service health",
      description:
        "Check configured services. Report exceptions and recoveries.",
      prompt:
        "Check availability and error logs for configured services. Report exceptions and recoveries only. Do not restart services.",
      minutes: "15",
    },
  ],
};
